wwwdocs: add a Python postprocessing script
The heading elements in our website contain "id" information,
but currently to find them you to look at the page source,
whereas in the generated HTML for the manual we have e.g.:

  <a class="copiable-link" href="#index-mabi-1"> &para;</a>

which shows up nicely in the browser in e.g.
  https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html
as a pilcrow character when you hover over the link, which
you can then use to copy the URL to the clipboard.

It's *very* helpful to have easily shareable links to within pages.

The attached patch adds a postprocessing step to "bin" that
turns e.g.
  <h1 id="ID">TEXT</h1>
to:
  <h1 id="ID"><a href="#ID">TEXT</a></h1>

which makes it very easy to copy links in the generated website.

Hook this script into our general preprocessing script for web pages.

diff --git a/bin/preprocess b/bin/preprocess
--- a/bin/preprocess
+++ b/bin/preprocess
@@ -119,6 +119,14 @@ process_html_file()
         exit 1
     fi
 
+    # Run output.raw through a Python script, then overwrite it with the
+    # output from the script.
+    if ! python3 /www/gcc/bin/preprocess-html.py $TMPDIR/output.raw $TMPDIR/output.after-py; then
+        echo "preprocess-html.py failed; aborting."
+        exit 1
+    fi
+    mv $TMPDIR/output.after-py $TMPDIR/output.raw
+
     # Use sed to work around makeinfo 4.7 brokenness.
     # Use sed to work around MetaHTML brokenness wrt. <DIV>.
     # Then remove leading blank lines and single line comments.
