Check result of every MetaHTML invocation and abort in case of an error.

diff --git a/bin/preprocess b/bin/preprocess
--- a/bin/preprocess
+++ b/bin/preprocess
@@ -108,15 +108,21 @@ process_html_file()
     export PREPROCESS_FILE
 
     # Prepend the MetaHTML style, set the MetaHTML include directory,
-    # and process the page; then remove leading blank lines and single
-    # line comments.
+    # and process the page.
 
     cat $STYLE > $TMPDIR/input
     printf '<set-var MHTML::INCLUDE-PREFIX="%s">\n' `pwd` >> $TMPDIR/input
     cat $f >> $TMPDIR/input
+
+    if ! ${MHC} $TMPDIR/input > $TMPDIR/output.raw; then
+        echo "${MHC} failed; aborting."
+        exit 1
+    fi
+
+    # Then remove leading blank lines and single line comments.
     # Use sed to work around makeinfo 4.7 brokenness.
     # Use sed to work around MetaHTML brokenness wrt. <DIV>.
-    ${MHC} $TMPDIR/input \
+    cat $TMPDIR/output.raw \
         | sed -e 's/_002d/-/g' -e 's/_002a/*/g' \
         | sed -e 's/<DIV/<div/g' \
         | awk -- \
